<?php

namespace ContainerV3EoZTY;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_58q1hNaService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.58q1hNa' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.58q1hNa'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservationRepository' => ['privates', '.errored.uKXnfmD', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::userReservations()": the $reservationRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\ReservationRepository". Did you forget to add a use statement?'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'reservationRepository' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
