<?php

namespace ContainerRrzJFvV;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_0_ER2bService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.0.E_r2b' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.0.E_r2b'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'roomRepository' => ['privates', 'App\\Repository\\RoomRepository', 'getRoomRepositoryService', true],
        ], [
            'roomRepository' => 'App\\Repository\\RoomRepository',
        ]);
    }
}
