<?php

namespace ContainerUFKLEba;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_LYnVtwsService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.LYnVtws' shared service.
     *
     * @return \App\Controller\RoomRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\UserController::userReservations()": the $roomRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\RoomRepository". Did you forget to add a use statement?');
    }
}
