<?php

namespace ContainerUFKLEba;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_KJDG8baService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.KJDG8ba' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.KJDG8ba'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'reservationRepository' => ['privates', 'App\\Repository\\ReservationRepository', 'getReservationRepositoryService', true],
            'roomRepository' => ['privates', '.errored.LYnVtws', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::userReservations()": the $roomRepository argument is type-hinted with the non-existent class or interface: "App\\Controller\\RoomRepository". Did you forget to add a use statement?'],
            'userRepository' => ['privates', 'App\\Repository\\UserRepository', 'getUserRepositoryService', true],
        ], [
            'reservationRepository' => 'App\\Repository\\ReservationRepository',
            'roomRepository' => '?',
            'userRepository' => 'App\\Repository\\UserRepository',
        ]);
    }
}
