<?php

namespace ContainerOWTEFcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_F0G32JBService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.f0G32JB' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.f0G32JB'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['services', 'doctrine', 'getDoctrineService', false],
            'serializer' => ['privates', '.errored.s40pory', NULL, 'Cannot determine controller argument for "App\\Controller\\ReservationController::addReservation()": the $serializer argument is type-hinted with the non-existent class or interface: "App\\Controller\\SerializerInterface". Did you forget to add a use statement?'],
        ], [
            'doctrine' => '?',
            'serializer' => '?',
        ]);
    }
}
