<?php

namespace ContainerOWTEFcT;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_S40poryService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.s40pory' shared service.
     *
     * @return \App\Controller\SerializerInterface
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\ReservationController::addReservation()": the $serializer argument is type-hinted with the non-existent class or interface: "App\\Controller\\SerializerInterface". Did you forget to add a use statement?');
    }
}
