<?php

namespace ContainerHxkgfxH;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_Errored_W4h5_N_Service extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.errored.w4h5.n.' shared service.
     *
     * @return \App\Controller\Request
     */
    public static function do($container, $lazyLoad = true)
    {
        throw new RuntimeException('Cannot determine controller argument for "App\\Controller\\LoginController::login()": the $request argument is type-hinted with the non-existent class or interface: "App\\Controller\\Request". Did you forget to add a use statement?');
    }
}
