<?php

namespace ContainerNPV7cKe;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class get_ServiceLocator_NwTwqBDService extends App_KernelDevDebugContainer
{
    /**
     * Gets the private '.service_locator.NwTwqBD' shared service.
     *
     * @return \Symfony\Component\DependencyInjection\ServiceLocator
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['.service_locator.NwTwqBD'] = new \Symfony\Component\DependencyInjection\Argument\ServiceLocator($container->getService ??= $container->getService(...), [
            'doctrine' => ['privates', '.errored.PnG..TG', NULL, 'Cannot determine controller argument for "App\\Controller\\UserController::addUser()": the $doctrine argument is type-hinted with the non-existent class or interface: "App\\Controller\\ManagerRegistry". Did you forget to add a use statement?'],
        ], [
            'doctrine' => '?',
        ]);
    }
}
