<?php

namespace ContainerBS89dhN;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/*
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getRoomRepositoryService extends App_KernelProdContainer
{
    /*
     * Gets the private 'App\Repository\RoomRepository' shared autowired service.
     *
     * @return \App\Repository\RoomRepository
     */
    public static function do($container, $lazyLoad = true)
    {
        return $container->privates['App\\Repository\\RoomRepository'] = new \App\Repository\RoomRepository(($container->services['doctrine'] ?? self::getDoctrineService($container)));
    }
}
