<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerW6eFVkS\App_KernelTestDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerW6eFVkS/App_KernelTestDebugContainer.php') {
    touch(__DIR__.'/ContainerW6eFVkS.legacy');

    return;
}

if (!\class_exists(App_KernelTestDebugContainer::class, false)) {
    \class_alias(\ContainerW6eFVkS\App_KernelTestDebugContainer::class, App_KernelTestDebugContainer::class, false);
}

return new \ContainerW6eFVkS\App_KernelTestDebugContainer([
    'container.build_hash' => 'W6eFVkS',
    'container.build_id' => '59a33c5b',
    'container.build_time' => 1689096220,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerW6eFVkS');
