<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerReBKrx3\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerReBKrx3/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerReBKrx3.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerReBKrx3\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerReBKrx3\App_KernelDevDebugContainer([
    'container.build_hash' => 'ReBKrx3',
    'container.build_id' => '11922cad',
    'container.build_time' => 1686602077,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerReBKrx3');
