<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerHP34k71\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerHP34k71/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerHP34k71.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerHP34k71\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerHP34k71\App_KernelDevDebugContainer([
    'container.build_hash' => 'HP34k71',
    'container.build_id' => '5262de00',
    'container.build_time' => 1687456771,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerHP34k71');
