<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerO4uFXmD\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerO4uFXmD/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerO4uFXmD.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerO4uFXmD\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerO4uFXmD\App_KernelDevDebugContainer([
    'container.build_hash' => 'O4uFXmD',
    'container.build_id' => '68ca2dca',
    'container.build_time' => 1687768576,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerO4uFXmD');
